[package]
name = "genvideo"
version = "0.1.0"
edition = "2024"

[dependencies]
rply-codec = { path = "../codec" }
retro-rs = { version = "0.5.4", default-features=false, path = "../../retro-rs" }
ffmpeg-next = "8.0.0"
ringbuf = "0.4.8"
